// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package priceoracle

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

const (
	ScName        = "priceoracle"
	ScDescription = "priceoracle description"
	HScName       = wasmtypes.ScHname(0xb2c5d36a)
)

const (
	ParamAgentid = "agentid"
	ParamOwner   = "owner"
	ParamPrice   = "price"
)

const (
	ResultOwner = "owner"
	ResultPrice = "price"
)

const (
	StateApprovedList     = "approvedList"
	StateApprovedMap      = "approvedMap"
	StateLastPrice        = "lastPrice"
	StateOracleLastUpdate = "oracleLastUpdate"
	StateOraclePrice      = "oraclePrice"
	StateOwner            = "owner"
)

const (
	FuncApproveOracle = "approveOracle"
	FuncInit          = "init"
	FuncSetMiotaPrice = "setMiotaPrice"
	FuncSetOwner      = "setOwner"
	ViewGetMiotaPrice = "getMiotaPrice"
	ViewGetOwner      = "getOwner"
)

const (
	HFuncApproveOracle = wasmtypes.ScHname(0x8b446340)
	HFuncInit          = wasmtypes.ScHname(0x1f44d644)
	HFuncSetMiotaPrice = wasmtypes.ScHname(0x6a3062ba)
	HFuncSetOwner      = wasmtypes.ScHname(0x2a15fe7b)
	HViewGetMiotaPrice = wasmtypes.ScHname(0x0715e7a4)
	HViewGetOwner      = wasmtypes.ScHname(0x137107a6)
)
