// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//nolint:gocritic
package priceoracle

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type priceoracleEvents struct {
}

func (e priceoracleEvents) Price(price int64) {
	evt := wasmlib.NewEventEncoder("priceoracle.price")
	evt.Encode(wasmtypes.Int64ToString(price))
	evt.Emit()
}

func (e priceoracleEvents) PriceSet(price int64) {
	evt := wasmlib.NewEventEncoder("priceoracle.priceSet")
	evt.Encode(wasmtypes.Int64ToString(price))
	evt.Emit()
}
