// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package dtag

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "dtag"
	ScDescription = "Incentivized AI Training Casino"
	HScName       = wasmlib.ScHname(0xb56d6fe7)
)

const (
	ParamDescription          = "description"
	ParamH                    = "h"
	ParamImageId              = "imageId"
	ParamNumberOfImages       = "numberOfImages"
	ParamTagsRequiredPerImage = "tagsRequiredPerImage"
	ParamW                    = "w"
	ParamX                    = "x"
	ParamY                    = "y"
)

const (
	ResultImageId       = "imageId"
	ResultPlayerBets    = "playerBets"
	ResultPlaysPerImage = "playsPerImage"
	ResultResults       = "results"
)

const (
	StateBets                 = "bets"
	StateCreator              = "creator"
	StateDescription          = "description"
	StateNumberOfImages       = "numberOfImages"
	StatePendingPlays         = "pendingPlays"
	StatePlaysPerImage        = "playsPerImage"
	StateProcessedImages      = "processedImages"
	StateReward               = "reward"
	StateTaggedImages         = "taggedImages"
	StateTagsRequiredPerImage = "tagsRequiredPerImage"
)

const (
	FuncCreateGame       = "createGame"
	FuncEndGame          = "endGame"
	FuncRequestPlay      = "requestPlay"
	FuncSendTags         = "sendTags"
	ViewGetPlayerBets    = "getPlayerBets"
	ViewGetPlaysPerImage = "getPlaysPerImage"
	ViewGetResults       = "getResults"
)

const (
	HFuncCreateGame       = wasmlib.ScHname(0x585dcce2)
	HFuncEndGame          = wasmlib.ScHname(0xb2303ef2)
	HFuncRequestPlay      = wasmlib.ScHname(0x74f0bf82)
	HFuncSendTags         = wasmlib.ScHname(0xc31816cb)
	HViewGetPlayerBets    = wasmlib.ScHname(0x842b0ef5)
	HViewGetPlaysPerImage = wasmlib.ScHname(0x749519e8)
	HViewGetResults       = wasmlib.ScHname(0xc2ed9edb)
)
