// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package dtag

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "dtag"
	ScDescription = "Incentivized AI Training Casino"
	HScName       = wasmlib.ScHname(0xb56d6fe7)
)

const (
	ParamDescription          = wasmlib.Key("description")
	ParamH                    = wasmlib.Key("h")
	ParamImageId              = wasmlib.Key("imageId")
	ParamNumberOfImages       = wasmlib.Key("numberOfImages")
	ParamTagsRequiredPerImage = wasmlib.Key("tagsRequiredPerImage")
	ParamW                    = wasmlib.Key("w")
	ParamX                    = wasmlib.Key("x")
	ParamY                    = wasmlib.Key("y")
)

const (
	ResultImageId       = wasmlib.Key("imageId")
	ResultPlaysPerImage = wasmlib.Key("playsPerImage")
	ResultResults       = wasmlib.Key("results")
)

const (
	StateBets                 = wasmlib.Key("bets")
	StateCreator              = wasmlib.Key("creator")
	StateDescription          = wasmlib.Key("description")
	StateNumberOfImages       = wasmlib.Key("numberOfImages")
	StatePendingPlays         = wasmlib.Key("pendingPlays")
	StatePlaysPerImage        = wasmlib.Key("playsPerImage")
	StateProcessedImages      = wasmlib.Key("processedImages")
	StateReward               = wasmlib.Key("reward")
	StateTaggedImages         = wasmlib.Key("taggedImages")
	StateTagsRequiredPerImage = wasmlib.Key("tagsRequiredPerImage")
)

const (
	FuncCreateGame       = "createGame"
	FuncEndGame          = "endGame"
	FuncRequestPlay      = "requestPlay"
	FuncSendTags         = "sendTags"
	ViewGetPlaysPerImage = "getPlaysPerImage"
	ViewGetResults       = "getResults"
)

const (
	HFuncCreateGame       = wasmlib.ScHname(0x585dcce2)
	HFuncEndGame          = wasmlib.ScHname(0xb2303ef2)
	HFuncRequestPlay      = wasmlib.ScHname(0x74f0bf82)
	HFuncSendTags         = wasmlib.ScHname(0xc31816cb)
	HViewGetPlaysPerImage = wasmlib.ScHname(0x749519e8)
	HViewGetResults       = wasmlib.ScHname(0xc2ed9edb)
)
