// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package dtag

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamBoost                = 0
	IdxParamDescription          = 1
	IdxParamH                    = 2
	IdxParamImageId              = 3
	IdxParamNumberOfImages       = 4
	IdxParamOwner                = 5
	IdxParamTagsRequiredPerImage = 6
	IdxParamW                    = 7
	IdxParamX                    = 8
	IdxParamY                    = 9

	IdxResultImageId       = 10
	IdxResultOwner         = 11
	IdxResultPlayerBets    = 12
	IdxResultPlaysPerImage = 13
	IdxResultResults       = 14

	IdxStateBets                 = 15
	IdxStateCreator              = 16
	IdxStateDescription          = 17
	IdxStateNumberOfImages       = 18
	IdxStateOwner                = 19
	IdxStatePendingPlays         = 20
	IdxStatePlaysPerImage        = 21
	IdxStateProcessedImages      = 22
	IdxStateReward               = 23
	IdxStateTaggedImages         = 24
	IdxStateTagsRequiredPerImage = 25
	IdxStateValidTags            = 26
)

const keyMapLen = 27

var keyMap = [keyMapLen]wasmlib.Key{
	ParamBoost,
	ParamDescription,
	ParamH,
	ParamImageId,
	ParamNumberOfImages,
	ParamOwner,
	ParamTagsRequiredPerImage,
	ParamW,
	ParamX,
	ParamY,
	ResultImageId,
	ResultOwner,
	ResultPlayerBets,
	ResultPlaysPerImage,
	ResultResults,
	StateBets,
	StateCreator,
	StateDescription,
	StateNumberOfImages,
	StateOwner,
	StatePendingPlays,
	StatePlaysPerImage,
	StateProcessedImages,
	StateReward,
	StateTaggedImages,
	StateTagsRequiredPerImage,
	StateValidTags,
}

var idxMap [keyMapLen]wasmlib.Key32
