// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package dtag

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamDescription          = 0
	IdxParamH                    = 1
	IdxParamImageId              = 2
	IdxParamNumberOfImages       = 3
	IdxParamTagsRequiredPerImage = 4
	IdxParamW                    = 5
	IdxParamX                    = 6
	IdxParamY                    = 7

	IdxResultImageId       = 8
	IdxResultPlayerBets    = 9
	IdxResultPlaysPerImage = 10
	IdxResultResults       = 11

	IdxStateBets                 = 12
	IdxStateCreator              = 13
	IdxStateDescription          = 14
	IdxStateNumberOfImages       = 15
	IdxStatePendingPlays         = 16
	IdxStatePlaysPerImage        = 17
	IdxStateProcessedImages      = 18
	IdxStateReward               = 19
	IdxStateTaggedImages         = 20
	IdxStateTagsRequiredPerImage = 21
)

const keyMapLen = 22

var keyMap = [keyMapLen]wasmlib.Key{
	ParamDescription,
	ParamH,
	ParamImageId,
	ParamNumberOfImages,
	ParamTagsRequiredPerImage,
	ParamW,
	ParamX,
	ParamY,
	ResultImageId,
	ResultPlayerBets,
	ResultPlaysPerImage,
	ResultResults,
	StateBets,
	StateCreator,
	StateDescription,
	StateNumberOfImages,
	StatePendingPlays,
	StatePlaysPerImage,
	StateProcessedImages,
	StateReward,
	StateTaggedImages,
	StateTagsRequiredPerImage,
}

var idxMap [keyMapLen]wasmlib.Key32
