// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmtypes from "wasmlib/wasmtypes";

export const ScName        = "priceoracle";
export const ScDescription = "priceoracle description";
export const HScName       = new wasmtypes.ScHname(0xb2c5d36a);

export const ParamAgentid = "agentid";
export const ParamOwner   = "owner";
export const ParamPrice   = "price";

export const ResultOwner = "owner";
export const ResultPrice = "price";

export const StateApprovedList     = "approvedList";
export const StateApprovedMap      = "approvedMap";
export const StateLastPrice        = "lastPrice";
export const StateOracleLastUpdate = "oracleLastUpdate";
export const StateOraclePrice      = "oraclePrice";
export const StateOwner            = "owner";

export const FuncApproveOracle = "approveOracle";
export const FuncInit          = "init";
export const FuncSetMiotaPrice = "setMiotaPrice";
export const FuncSetOwner      = "setOwner";
export const ViewGetMiotaPrice = "getMiotaPrice";
export const ViewGetOwner      = "getOwner";

export const HFuncApproveOracle = new wasmtypes.ScHname(0x8b446340);
export const HFuncInit          = new wasmtypes.ScHname(0x1f44d644);
export const HFuncSetMiotaPrice = new wasmtypes.ScHname(0x6a3062ba);
export const HFuncSetOwner      = new wasmtypes.ScHname(0x2a15fe7b);
export const HViewGetMiotaPrice = new wasmtypes.ScHname(0x0715e7a4);
export const HViewGetOwner      = new wasmtypes.ScHname(0x137107a6);
