// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

const exportMap: wasmlib.ScExportMap = {
	names: [
		sc.FuncApproveOracle,
		sc.FuncInit,
		sc.FuncSetMiotaPrice,
		sc.FuncSetOwner,
		sc.ViewGetMiotaPrice,
		sc.ViewGetOwner,
	],
	funcs: [
		funcApproveOracleThunk,
		funcInitThunk,
		funcSetMiotaPriceThunk,
		funcSetOwnerThunk,
	],
	views: [
		viewGetMiotaPriceThunk,
		viewGetOwnerThunk,
	],
};

export function on_call(index: i32): void {
	wasmlib.ScExports.call(index, exportMap);
}

export function on_load(): void {
	wasmlib.ScExports.export(exportMap);
}

function funcApproveOracleThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("priceoracle.funcApproveOracle");
	let f = new sc.ApproveOracleContext();

	// current owner of this smart contract
	const access = f.state.owner();
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller().equals(access.value()), "no permission");

	ctx.require(f.params.agentid().exists(), "missing mandatory agentid");
	sc.funcApproveOracle(ctx, f);
	ctx.log("priceoracle.funcApproveOracle ok");
}

function funcInitThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("priceoracle.funcInit");
	let f = new sc.InitContext();
	sc.funcInit(ctx, f);
	ctx.log("priceoracle.funcInit ok");
}

function funcSetMiotaPriceThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("priceoracle.funcSetMiotaPrice");
	let f = new sc.SetMiotaPriceContext();
	ctx.require(f.params.price().exists(), "missing mandatory price");
	sc.funcSetMiotaPrice(ctx, f);
	ctx.log("priceoracle.funcSetMiotaPrice ok");
}

function funcSetOwnerThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("priceoracle.funcSetOwner");
	let f = new sc.SetOwnerContext();

	// current owner of this smart contract
	const access = f.state.owner();
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller().equals(access.value()), "no permission");

	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	sc.funcSetOwner(ctx, f);
	ctx.log("priceoracle.funcSetOwner ok");
}

function viewGetMiotaPriceThunk(ctx: wasmlib.ScViewContext): void {
	ctx.log("priceoracle.viewGetMiotaPrice");
	let f = new sc.GetMiotaPriceContext();
	const results = new wasmlib.ScDict([]);
	f.results = new sc.MutableGetMiotaPriceResults(results.asProxy());
	sc.viewGetMiotaPrice(ctx, f);
	ctx.results(results);
	ctx.log("priceoracle.viewGetMiotaPrice ok");
}

function viewGetOwnerThunk(ctx: wasmlib.ScViewContext): void {
	ctx.log("priceoracle.viewGetOwner");
	let f = new sc.GetOwnerContext();
	const results = new wasmlib.ScDict([]);
	f.results = new sc.MutableGetOwnerResults(results.asProxy());
	sc.viewGetOwner(ctx, f);
	ctx.results(results);
	ctx.log("priceoracle.viewGetOwner ok");
}
