// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package giveaway

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAddresses = 0
	IdxParamNWinners  = 1
	IdxParamOwner     = 2

	IdxResultOwner   = 3
	IdxResultWinners = 4

	IdxStateAddresses = 5
	IdxStateOwner     = 6
)

const keyMapLen = 7

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAddresses,
	ParamNWinners,
	ParamOwner,
	ResultOwner,
	ResultWinners,
	StateAddresses,
	StateOwner,
}

var idxMap [keyMapLen]wasmlib.Key32
