// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package giveaway

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ImmutableInitParams struct {
	id int32
}

func (s ImmutableInitParams) Owner() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamOwner])
}

type MutableInitParams struct {
	id int32
}

func (s MutableInitParams) Owner() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamOwner])
}

type ImmutableLoadAddressesParams struct {
	id int32
}

func (s ImmutableLoadAddressesParams) Addresses() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamAddresses])
}

type MutableLoadAddressesParams struct {
	id int32
}

func (s MutableLoadAddressesParams) Addresses() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamAddresses])
}

type ImmutableRuffleParams struct {
	id int32
}

func (s ImmutableRuffleParams) NWinners() wasmlib.ScImmutableInt16 {
	return wasmlib.NewScImmutableInt16(s.id, idxMap[IdxParamNWinners])
}

type MutableRuffleParams struct {
	id int32
}

func (s MutableRuffleParams) NWinners() wasmlib.ScMutableInt16 {
	return wasmlib.NewScMutableInt16(s.id, idxMap[IdxParamNWinners])
}

type ImmutableSetOwnerParams struct {
	id int32
}

func (s ImmutableSetOwnerParams) Owner() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamOwner])
}

type MutableSetOwnerParams struct {
	id int32
}

func (s MutableSetOwnerParams) Owner() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamOwner])
}
