// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME:        &str = "dtag";
pub const SC_DESCRIPTION: &str = "Agricultural AI Training Casino";
pub const HSC_NAME:       ScHname = ScHname(0xb56d6fe7);

pub const PARAM_DESCRIPTION:      &str = "description";
pub const PARAM_IMAGE_ID:         &str = "imageId";
pub const PARAM_NUMBER_OF_IMAGES: &str = "numberOfImages";
pub const PARAM_OWNER:            &str = "owner";
pub const PARAM_TAG:              &str = "tag";

pub const RESULT_PLAYS_PER_IMAGE:  &str = "playsPerImage";
pub const RESULT_PROCESSED_IMAGES: &str = "processedImages";
pub const RESULT_TAGGED_IMAGES:    &str = "taggedImages";

pub const STATE_NUMBER_OF_IMAGES: &str = "numberOfImages";
pub const STATE_OWNER:            &str = "owner";
pub const STATE_PLAYS_PER_IMAGE:  &str = "playsPerImage";
pub const STATE_PROCESSED_IMAGES: &str = "processedImages";
pub const STATE_TAGGED_IMAGES:    &str = "taggedImages";

pub const FUNC_ASSIGN_IMAGE:        &str = "assignImage";
pub const FUNC_CREATE_GAME:         &str = "createGame";
pub const FUNC_END_GAME:            &str = "endGame";
pub const FUNC_INIT:                &str = "init";
pub const FUNC_REQUEST_PLAY:        &str = "requestPlay";
pub const FUNC_SEND_TAG:            &str = "sendTag";
pub const VIEW_GET_PLAYS_PER_IMAGE: &str = "getPlaysPerImage";
pub const VIEW_GET_RESULTS:         &str = "getResults";
pub const VIEW_GET_TAGGED_IMAGES:   &str = "getTaggedImages";

pub const HFUNC_ASSIGN_IMAGE:        ScHname = ScHname(0x71a5077f);
pub const HFUNC_CREATE_GAME:         ScHname = ScHname(0x585dcce2);
pub const HFUNC_END_GAME:            ScHname = ScHname(0xb2303ef2);
pub const HFUNC_INIT:                ScHname = ScHname(0x1f44d644);
pub const HFUNC_REQUEST_PLAY:        ScHname = ScHname(0x74f0bf82);
pub const HFUNC_SEND_TAG:            ScHname = ScHname(0xcc9710cc);
pub const HVIEW_GET_PLAYS_PER_IMAGE: ScHname = ScHname(0x749519e8);
pub const HVIEW_GET_RESULTS:         ScHname = ScHname(0xc2ed9edb);
pub const HVIEW_GET_TAGGED_IMAGES:   ScHname = ScHname(0xeec48252);

// @formatter:on
