// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub(crate) const IDX_PARAM_DESCRIPTION:       usize = 0;
pub(crate) const IDX_PARAM_IMAGE_ID:          usize = 1;
pub(crate) const IDX_PARAM_NUMBER_OF_IMAGES:  usize = 2;
pub(crate) const IDX_PARAM_OWNER:             usize = 3;
pub(crate) const IDX_PARAM_TAG:               usize = 4;
pub(crate) const IDX_RESULT_PLAYS_PER_IMAGE:  usize = 5;
pub(crate) const IDX_RESULT_PROCESSED_IMAGES: usize = 6;
pub(crate) const IDX_RESULT_TAGGED_IMAGES:    usize = 7;
pub(crate) const IDX_STATE_NUMBER_OF_IMAGES:  usize = 8;
pub(crate) const IDX_STATE_OWNER:             usize = 9;
pub(crate) const IDX_STATE_PLAYS_PER_IMAGE:   usize = 10;
pub(crate) const IDX_STATE_PROCESSED_IMAGES:  usize = 11;
pub(crate) const IDX_STATE_TAGGED_IMAGES:     usize = 12;

pub const KEY_MAP_LEN: usize = 13;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
    PARAM_DESCRIPTION,
    PARAM_IMAGE_ID,
    PARAM_NUMBER_OF_IMAGES,
    PARAM_OWNER,
    PARAM_TAG,
    RESULT_PLAYS_PER_IMAGE,
    RESULT_PROCESSED_IMAGES,
    RESULT_TAGGED_IMAGES,
    STATE_NUMBER_OF_IMAGES,
    STATE_OWNER,
    STATE_PLAYS_PER_IMAGE,
    STATE_PROCESSED_IMAGES,
    STATE_TAGGED_IMAGES,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}

// @formatter:on
