// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;
use wasmlib::host::*;

pub struct Bet {
    pub amount   : i64, 
    pub image_id : i32, 
    pub player   : ScAgentID,  // player placing the bet
}

impl Bet {
    pub fn from_bytes(bytes: &[u8]) -> Bet {
        let mut decode = BytesDecoder::new(bytes);
        Bet {
            amount   : decode.int64(),
            image_id : decode.int32(),
            player   : decode.agent_id(),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut encode = BytesEncoder::new();
		encode.int64(self.amount);
		encode.int32(self.image_id);
		encode.agent_id(&self.player);
        return encode.data();
    }
}

pub struct ImmutableBet {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl ImmutableBet {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn value(&self) -> Bet {
        Bet::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}

pub struct MutableBet {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl MutableBet {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn set_value(&self, value: &Bet) {
        set_bytes(self.obj_id, self.key_id, TYPE_BYTES, &value.to_bytes());
    }

    pub fn value(&self) -> Bet {
        Bet::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}

pub struct TaggedImage {
    pub boost    : String,  // if the tags will be boosted or not
    pub h        : String,  // heights of the Tags
    pub image_id : i32, 
    pub player   : ScAgentID,  // player that has tagged this image
    pub w        : String,  // widths of the Tags
    pub x        : String,  // x top-left positions of the Tags
    pub y        : String,  // y top-left positions of the Tags
}

impl TaggedImage {
    pub fn from_bytes(bytes: &[u8]) -> TaggedImage {
        let mut decode = BytesDecoder::new(bytes);
        TaggedImage {
            boost    : decode.string(),
            h        : decode.string(),
            image_id : decode.int32(),
            player   : decode.agent_id(),
            w        : decode.string(),
            x        : decode.string(),
            y        : decode.string(),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut encode = BytesEncoder::new();
		encode.string(&self.boost);
		encode.string(&self.h);
		encode.int32(self.image_id);
		encode.agent_id(&self.player);
		encode.string(&self.w);
		encode.string(&self.x);
		encode.string(&self.y);
        return encode.data();
    }
}

pub struct ImmutableTaggedImage {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl ImmutableTaggedImage {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn value(&self) -> TaggedImage {
        TaggedImage::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}

pub struct MutableTaggedImage {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl MutableTaggedImage {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn set_value(&self, value: &TaggedImage) {
        set_bytes(self.obj_id, self.key_id, TYPE_BYTES, &value.to_bytes());
    }

    pub fn value(&self) -> TaggedImage {
        TaggedImage::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}

pub struct ValidTag {
    pub play_tag_id  : i32,  // Identifier to distinguish different tags in the same play
    pub player       : ScAgentID,  // player placing the bet
    pub tagged_image : i32, 
}

impl ValidTag {
    pub fn from_bytes(bytes: &[u8]) -> ValidTag {
        let mut decode = BytesDecoder::new(bytes);
        ValidTag {
            play_tag_id  : decode.int32(),
            player       : decode.agent_id(),
            tagged_image : decode.int32(),
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut encode = BytesEncoder::new();
		encode.int32(self.play_tag_id);
		encode.agent_id(&self.player);
		encode.int32(self.tagged_image);
        return encode.data();
    }
}

pub struct ImmutableValidTag {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl ImmutableValidTag {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn value(&self) -> ValidTag {
        ValidTag::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}

pub struct MutableValidTag {
    pub(crate) obj_id: i32,
    pub(crate) key_id: Key32,
}

impl MutableValidTag {
    pub fn exists(&self) -> bool {
        exists(self.obj_id, self.key_id, TYPE_BYTES)
    }

    pub fn set_value(&self, value: &ValidTag) {
        set_bytes(self.obj_id, self.key_id, TYPE_BYTES, &value.to_bytes());
    }

    pub fn value(&self) -> ValidTag {
        ValidTag::from_bytes(&get_bytes(self.obj_id, self.key_id, TYPE_BYTES))
    }
}
