// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "priceoracle";
pub const SC_DESCRIPTION : &str = "priceoracle description";
pub const HSC_NAME       : ScHname = ScHname(0xb2c5d36a);

pub const PARAM_AGENTID : &str = "agentid";
pub const PARAM_OWNER   : &str = "owner";
pub const PARAM_PRICE   : &str = "price";

pub const RESULT_OWNER : &str = "owner";
pub const RESULT_PRICE : &str = "price";

pub const STATE_APPROVED_LIST      : &str = "approvedList";
pub const STATE_APPROVED_MAP       : &str = "approvedMap";
pub const STATE_LAST_PRICE         : &str = "lastPrice";
pub const STATE_ORACLE_LAST_UPDATE : &str = "oracleLastUpdate";
pub const STATE_ORACLE_PRICE       : &str = "oraclePrice";
pub const STATE_OWNER              : &str = "owner";

pub const FUNC_APPROVE_ORACLE  : &str = "approveOracle";
pub const FUNC_INIT            : &str = "init";
pub const FUNC_SET_MIOTA_PRICE : &str = "setMiotaPrice";
pub const FUNC_SET_OWNER       : &str = "setOwner";
pub const VIEW_GET_MIOTA_PRICE : &str = "getMiotaPrice";
pub const VIEW_GET_OWNER       : &str = "getOwner";

pub const HFUNC_APPROVE_ORACLE  : ScHname = ScHname(0x8b446340);
pub const HFUNC_INIT            : ScHname = ScHname(0x1f44d644);
pub const HFUNC_SET_MIOTA_PRICE : ScHname = ScHname(0x6a3062ba);
pub const HFUNC_SET_OWNER       : ScHname = ScHname(0x2a15fe7b);
pub const HVIEW_GET_MIOTA_PRICE : ScHname = ScHname(0x0715e7a4);
pub const HVIEW_GET_OWNER       : ScHname = ScHname(0x137107a6);
