// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct priceoracleEvents {
}

impl priceoracleEvents {

	pub fn price(&self, price: i64) {
		let mut evt = EventEncoder::new("priceoracle.price");
		evt.encode(&int64_to_string(price));
		evt.emit();
	}

	pub fn price_set(&self, price: i64) {
		let mut evt = EventEncoder::new("priceoracle.priceSet");
		evt.encode(&int64_to_string(price));
		evt.emit();
	}
}
