// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "zentangle";
pub const SC_DESCRIPTION : &str = "Incentivized AI Training Casino";
pub const HSC_NAME       : ScHname = ScHname(0xf707a9c6);

pub const PARAM_DESCRIPTION             : &str = "description";
pub const PARAM_IMAGE_ID                : &str = "imageId";
pub const PARAM_INPUT_JSON              : &str = "inputJson";
pub const PARAM_NUMBER_OF_IMAGES        : &str = "numberOfImages";
pub const PARAM_OWNER                   : &str = "owner";
pub const PARAM_TAGS_REQUIRED_PER_IMAGE : &str = "tagsRequiredPerImage";

pub const RESULT_IMAGE_ID        : &str = "imageId";
pub const RESULT_OWNER           : &str = "owner";
pub const RESULT_PLAYER_BETS     : &str = "playerBets";
pub const RESULT_PLAYS_PER_IMAGE : &str = "playsPerImage";
pub const RESULT_RESULTS         : &str = "results";

pub const STATE_BETS                    : &str = "bets";
pub const STATE_CREATOR                 : &str = "creator";
pub const STATE_DESCRIPTION             : &str = "description";
pub const STATE_NUMBER_OF_IMAGES        : &str = "numberOfImages";
pub const STATE_OWNER                   : &str = "owner";
pub const STATE_PENDING_PLAYS           : &str = "pendingPlays";
pub const STATE_PLAYERS                 : &str = "players";
pub const STATE_PLAYS_PER_IMAGE         : &str = "playsPerImage";
pub const STATE_PROCESSED_IMAGES        : &str = "processedImages";
pub const STATE_REWARD                  : &str = "reward";
pub const STATE_TAGGED_IMAGES           : &str = "taggedImages";
pub const STATE_TAGS_REQUIRED_PER_IMAGE : &str = "tagsRequiredPerImage";
pub const STATE_VALID_TAGS              : &str = "validTags";

pub const FUNC_CREATE_GAME         : &str = "createGame";
pub const FUNC_END_GAME            : &str = "endGame";
pub const FUNC_INIT                : &str = "init";
pub const FUNC_REQUEST_PLAY        : &str = "requestPlay";
pub const FUNC_SEND_TAGS           : &str = "sendTags";
pub const FUNC_SET_OWNER           : &str = "setOwner";
pub const FUNC_WITHDRAW            : &str = "withdraw";
pub const VIEW_GET_OWNER           : &str = "getOwner";
pub const VIEW_GET_PLAYER_BETS     : &str = "getPlayerBets";
pub const VIEW_GET_PLAYS_PER_IMAGE : &str = "getPlaysPerImage";
pub const VIEW_GET_RESULTS         : &str = "getResults";

pub const HFUNC_CREATE_GAME         : ScHname = ScHname(0x585dcce2);
pub const HFUNC_END_GAME            : ScHname = ScHname(0xb2303ef2);
pub const HFUNC_INIT                : ScHname = ScHname(0x1f44d644);
pub const HFUNC_REQUEST_PLAY        : ScHname = ScHname(0x74f0bf82);
pub const HFUNC_SEND_TAGS           : ScHname = ScHname(0xc31816cb);
pub const HFUNC_SET_OWNER           : ScHname = ScHname(0x2a15fe7b);
pub const HFUNC_WITHDRAW            : ScHname = ScHname(0x9dcc0f41);
pub const HVIEW_GET_OWNER           : ScHname = ScHname(0x137107a6);
pub const HVIEW_GET_PLAYER_BETS     : ScHname = ScHname(0x842b0ef5);
pub const HVIEW_GET_PLAYS_PER_IMAGE : ScHname = ScHname(0x749519e8);
pub const HVIEW_GET_RESULTS         : ScHname = ScHname(0xc2ed9edb);
