// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub struct zentangleEvents {
}

impl zentangleEvents {

	pub fn game_ended(&self) {
		EventEncoder::new("zentangle.gameEnded").emit();
	}

	pub fn game_started(&self, description: &str, number_of_images: i32, reward: i64, tags_required_per_image: i32) {
		let mut encoder = EventEncoder::new("zentangle.gameStarted");
		encoder.string(&description);
		encoder.int32(number_of_images);
		encoder.int64(reward);
		encoder.int32(tags_required_per_image);
		encoder.emit();
	}

	pub fn imagetagged(&self, address: &str, image_id: i32, plays_per_image: i32) {
		let mut encoder = EventEncoder::new("zentangle.imagetagged");
		encoder.string(&address);
		encoder.int32(image_id);
		encoder.int32(plays_per_image);
		encoder.emit();
	}

	pub fn play_requested(&self, adress: &str, amount: i64, image_id: i32) {
		let mut encoder = EventEncoder::new("zentangle.playRequested");
		encoder.string(&adress);
		encoder.int64(amount);
		encoder.int32(image_id);
		encoder.emit();
	}
}
