// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub(crate) const IDX_PARAM_DESCRIPTION             : usize = 0;
pub(crate) const IDX_PARAM_IMAGE_ID                : usize = 1;
pub(crate) const IDX_PARAM_INPUT_JSON              : usize = 2;
pub(crate) const IDX_PARAM_NUMBER_OF_IMAGES        : usize = 3;
pub(crate) const IDX_PARAM_OWNER                   : usize = 4;
pub(crate) const IDX_PARAM_PLAYER_ADDRESS          : usize = 5;
pub(crate) const IDX_PARAM_RESET_PLAYER_INFO       : usize = 6;
pub(crate) const IDX_PARAM_TAGS_REQUIRED_PER_IMAGE : usize = 7;

pub(crate) const IDX_RESULT_IMAGE_ID        : usize = 8;
pub(crate) const IDX_RESULT_INFO            : usize = 9;
pub(crate) const IDX_RESULT_OWNER           : usize = 10;
pub(crate) const IDX_RESULT_PLAYER_BETS     : usize = 11;
pub(crate) const IDX_RESULT_PLAYS_PER_IMAGE : usize = 12;
pub(crate) const IDX_RESULT_RESULTS         : usize = 13;

pub(crate) const IDX_STATE_BETS                    : usize = 14;
pub(crate) const IDX_STATE_CREATOR                 : usize = 15;
pub(crate) const IDX_STATE_DESCRIPTION             : usize = 16;
pub(crate) const IDX_STATE_NUMBER_OF_IMAGES        : usize = 17;
pub(crate) const IDX_STATE_OWNER                   : usize = 18;
pub(crate) const IDX_STATE_PENDING_PLAY            : usize = 19;
pub(crate) const IDX_STATE_PLAYER                  : usize = 20;
pub(crate) const IDX_STATE_PLAYS_PER_IMAGE         : usize = 21;
pub(crate) const IDX_STATE_PROCESSED_IMAGES        : usize = 22;
pub(crate) const IDX_STATE_REWARD                  : usize = 23;
pub(crate) const IDX_STATE_TAGGED_IMAGES           : usize = 24;
pub(crate) const IDX_STATE_TAGS_REQUIRED_PER_IMAGE : usize = 25;
pub(crate) const IDX_STATE_VALID_TAGS              : usize = 26;

pub const KEY_MAP_LEN: usize = 27;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
	PARAM_DESCRIPTION,
	PARAM_IMAGE_ID,
	PARAM_INPUT_JSON,
	PARAM_NUMBER_OF_IMAGES,
	PARAM_OWNER,
	PARAM_PLAYER_ADDRESS,
	PARAM_RESET_PLAYER_INFO,
	PARAM_TAGS_REQUIRED_PER_IMAGE,
	RESULT_IMAGE_ID,
	RESULT_INFO,
	RESULT_OWNER,
	RESULT_PLAYER_BETS,
	RESULT_PLAYS_PER_IMAGE,
	RESULT_RESULTS,
	STATE_BETS,
	STATE_CREATOR,
	STATE_DESCRIPTION,
	STATE_NUMBER_OF_IMAGES,
	STATE_OWNER,
	STATE_PENDING_PLAY,
	STATE_PLAYER,
	STATE_PLAYS_PER_IMAGE,
	STATE_PROCESSED_IMAGES,
	STATE_REWARD,
	STATE_TAGGED_IMAGES,
	STATE_TAGS_REQUIRED_PER_IMAGE,
	STATE_VALID_TAGS,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}
