// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;
use crate::*;

#[derive(Clone)]
pub struct ImmutableCreateGameParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableCreateGameParams {
    pub fn description(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_DESCRIPTION))
	}

    pub fn number_of_images(&self) -> ScImmutableUint32 {
		ScImmutableUint32::new(self.proxy.root(PARAM_NUMBER_OF_IMAGES))
	}

    pub fn tags_required_per_image(&self) -> ScImmutableUint32 {
		ScImmutableUint32::new(self.proxy.root(PARAM_TAGS_REQUIRED_PER_IMAGE))
	}
}

#[derive(Clone)]
pub struct MutableCreateGameParams {
	pub(crate) proxy: Proxy,
}

impl MutableCreateGameParams {
    pub fn description(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_DESCRIPTION))
	}

    pub fn number_of_images(&self) -> ScMutableUint32 {
		ScMutableUint32::new(self.proxy.root(PARAM_NUMBER_OF_IMAGES))
	}

    pub fn tags_required_per_image(&self) -> ScMutableUint32 {
		ScMutableUint32::new(self.proxy.root(PARAM_TAGS_REQUIRED_PER_IMAGE))
	}
}

#[derive(Clone)]
pub struct ImmutableEndGameParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableEndGameParams {
    pub fn mission(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_MISSION))
	}

    pub fn reset_player_info(&self) -> ScImmutableBool {
		ScImmutableBool::new(self.proxy.root(PARAM_RESET_PLAYER_INFO))
	}
}

#[derive(Clone)]
pub struct MutableEndGameParams {
	pub(crate) proxy: Proxy,
}

impl MutableEndGameParams {
    pub fn mission(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_MISSION))
	}

    pub fn reset_player_info(&self) -> ScMutableBool {
		ScMutableBool::new(self.proxy.root(PARAM_RESET_PLAYER_INFO))
	}
}

#[derive(Clone)]
pub struct ImmutableInitParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableInitParams {
    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct MutableInitParams {
	pub(crate) proxy: Proxy,
}

impl MutableInitParams {
    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct ImmutableSendTagsParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSendTagsParams {
    pub fn input_json(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_INPUT_JSON))
	}
}

#[derive(Clone)]
pub struct MutableSendTagsParams {
	pub(crate) proxy: Proxy,
}

impl MutableSendTagsParams {
    pub fn input_json(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_INPUT_JSON))
	}
}

#[derive(Clone)]
pub struct ImmutableSetOwnerParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableSetOwnerParams {
    pub fn owner(&self) -> ScImmutableAgentID {
		ScImmutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct MutableSetOwnerParams {
	pub(crate) proxy: Proxy,
}

impl MutableSetOwnerParams {
    pub fn owner(&self) -> ScMutableAgentID {
		ScMutableAgentID::new(self.proxy.root(PARAM_OWNER))
	}
}

#[derive(Clone)]
pub struct ImmutableGetPlayerInfoParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableGetPlayerInfoParams {
    pub fn player_address(&self) -> ScImmutableString {
		ScImmutableString::new(self.proxy.root(PARAM_PLAYER_ADDRESS))
	}
}

#[derive(Clone)]
pub struct MutableGetPlayerInfoParams {
	pub(crate) proxy: Proxy,
}

impl MutableGetPlayerInfoParams {
    pub fn player_address(&self) -> ScMutableString {
		ScMutableString::new(self.proxy.root(PARAM_PLAYER_ADDRESS))
	}
}

#[derive(Clone)]
pub struct ImmutableGetPlaysPerImageParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableGetPlaysPerImageParams {
    pub fn image_id(&self) -> ScImmutableUint32 {
		ScImmutableUint32::new(self.proxy.root(PARAM_IMAGE_ID))
	}
}

#[derive(Clone)]
pub struct MutableGetPlaysPerImageParams {
	pub(crate) proxy: Proxy,
}

impl MutableGetPlaysPerImageParams {
    pub fn image_id(&self) -> ScMutableUint32 {
		ScMutableUint32::new(self.proxy.root(PARAM_IMAGE_ID))
	}
}

#[derive(Clone)]
pub struct ImmutableGetResultsParams {
	pub(crate) proxy: Proxy,
}

impl ImmutableGetResultsParams {
    pub fn image_id(&self) -> ScImmutableUint32 {
		ScImmutableUint32::new(self.proxy.root(PARAM_IMAGE_ID))
	}
}

#[derive(Clone)]
pub struct MutableGetResultsParams {
	pub(crate) proxy: Proxy,
}

impl MutableGetResultsParams {
    pub fn image_id(&self) -> ScMutableUint32 {
		ScMutableUint32::new(self.proxy.root(PARAM_IMAGE_ID))
	}
}
