// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmclient from "wasmclient"
import * as app from "./zentangle"

export const eventHandlers: wasmclient.EventHandlers = {
	"zentangle.gameEnded": (msg: string[]) => app.onZentangleGameEnded(new EventGameEnded(msg)),
	"zentangle.gameStarted": (msg: string[]) => app.onZentangleGameStarted(new EventGameStarted(msg)),
	"zentangle.imagetagged": (msg: string[]) => app.onZentangleImagetagged(new EventImagetagged(msg)),
	"zentangle.paid": (msg: string[]) => app.onZentanglePaid(new EventPaid(msg)),
	"zentangle.playRequested": (msg: string[]) => app.onZentanglePlayRequested(new EventPlayRequested(msg)),
};

export class EventGameEnded extends wasmclient.Event {
	
	public constructor(msg: string[]) {
		super(msg)
	}
}

export class EventGameStarted extends wasmclient.Event {
	public readonly description: wasmclient.String;
	public readonly numberOfImages: wasmclient.Uint32;
	public readonly reward: wasmclient.Uint64;
	public readonly tagsRequiredPerImage: wasmclient.Uint32;
	
	public constructor(msg: string[]) {
		super(msg)
		this.description = this.nextString();
		this.numberOfImages = this.nextUint32();
		this.reward = this.nextUint64();
		this.tagsRequiredPerImage = this.nextUint32();
	}
}

export class EventImagetagged extends wasmclient.Event {
	public readonly address: wasmclient.String;
	public readonly imageId: wasmclient.Uint32;
	public readonly playsPerImage: wasmclient.Uint32;
	
	public constructor(msg: string[]) {
		super(msg)
		this.address = this.nextString();
		this.imageId = this.nextUint32();
		this.playsPerImage = this.nextUint32();
	}
}

export class EventPaid extends wasmclient.Event {
	public readonly accuracy: wasmclient.String;
	public readonly amount: wasmclient.Uint64;
	public readonly bet: wasmclient.Uint64;
	public readonly boost: wasmclient.Uint8;
	public readonly player: wasmclient.String;
	public readonly position: wasmclient.Uint64;
	
	public constructor(msg: string[]) {
		super(msg)
		this.accuracy = this.nextString();
		this.amount = this.nextUint64();
		this.bet = this.nextUint64();
		this.boost = this.nextUint8();
		this.player = this.nextString();
		this.position = this.nextUint64();
	}
}

export class EventPlayRequested extends wasmclient.Event {
	public readonly address: wasmclient.String;
	public readonly amount: wasmclient.Uint64;
	public readonly imageId: wasmclient.Uint32;
	
	public constructor(msg: string[]) {
		super(msg)
		this.address = this.nextString();
		this.amount = this.nextUint64();
		this.imageId = this.nextUint32();
	}
}
