// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;
use crate::*;

pub struct InitCall {
	pub func: ScInitFunc,
	pub params: MutableInitParams,
}

pub struct LoadAddressesCall {
	pub func: ScFunc,
	pub params: MutableLoadAddressesParams,
}

pub struct RuffleCall {
	pub func: ScFunc,
	pub params: MutableRuffleParams,
	pub results: ImmutableRuffleResults,
}

pub struct SetOwnerCall {
	pub func: ScFunc,
	pub params: MutableSetOwnerParams,
}

pub struct UnloadAddressesCall {
	pub func: ScFunc,
}

pub struct GetOwnerCall {
	pub func: ScView,
	pub results: ImmutableGetOwnerResults,
}

pub struct ScFuncs {
}

impl ScFuncs {
    pub fn init(_ctx: &dyn ScFuncCallContext) -> InitCall {
        let mut f = InitCall {
            func: ScInitFunc::new(HSC_NAME, HFUNC_INIT),
            params: MutableInitParams { proxy: Proxy::nil() },
        };
        ScInitFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn load_addresses(_ctx: &dyn ScFuncCallContext) -> LoadAddressesCall {
        let mut f = LoadAddressesCall {
            func: ScFunc::new(HSC_NAME, HFUNC_LOAD_ADDRESSES),
            params: MutableLoadAddressesParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn ruffle(_ctx: &dyn ScFuncCallContext) -> RuffleCall {
        let mut f = RuffleCall {
            func: ScFunc::new(HSC_NAME, HFUNC_RUFFLE),
            params: MutableRuffleParams { proxy: Proxy::nil() },
            results: ImmutableRuffleResults { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        ScFunc::link_results(&mut f.results.proxy, &f.func);
        f
    }

    pub fn set_owner(_ctx: &dyn ScFuncCallContext) -> SetOwnerCall {
        let mut f = SetOwnerCall {
            func: ScFunc::new(HSC_NAME, HFUNC_SET_OWNER),
            params: MutableSetOwnerParams { proxy: Proxy::nil() },
        };
        ScFunc::link_params(&mut f.params.proxy, &f.func);
        f
    }

    pub fn unload_addresses(_ctx: &dyn ScFuncCallContext) -> UnloadAddressesCall {
        UnloadAddressesCall {
            func: ScFunc::new(HSC_NAME, HFUNC_UNLOAD_ADDRESSES),
        }
    }

    pub fn get_owner(_ctx: &dyn ScViewCallContext) -> GetOwnerCall {
        let mut f = GetOwnerCall {
            func: ScView::new(HSC_NAME, HVIEW_GET_OWNER),
            results: ImmutableGetOwnerResults { proxy: Proxy::nil() },
        };
        ScView::link_results(&mut f.results.proxy, &f.func);
        f
    }
}
