// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub struct giveawayEvents {
}

impl giveawayEvents {

	pub fn winner(&self, evm_address: &str) {
		let mut encoder = EventEncoder::new("giveaway.winner");
		encoder.string(&evm_address);
		encoder.emit();
	}
}
