// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub(crate) const IDX_PARAM_ADDRESSES : usize = 0;
pub(crate) const IDX_PARAM_N_WINNERS : usize = 1;
pub(crate) const IDX_PARAM_OWNER     : usize = 2;

pub(crate) const IDX_RESULT_OWNER   : usize = 3;
pub(crate) const IDX_RESULT_WINNERS : usize = 4;

pub(crate) const IDX_STATE_ADDRESSES : usize = 5;
pub(crate) const IDX_STATE_OWNER     : usize = 6;

pub const KEY_MAP_LEN: usize = 7;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
	PARAM_ADDRESSES,
	PARAM_N_WINNERS,
	PARAM_OWNER,
	RESULT_OWNER,
	RESULT_WINNERS,
	STATE_ADDRESSES,
	STATE_OWNER,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}
