// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";

export class zentangleEvents {

	gameEnded(): void {
		new wasmlib.EventEncoder("zentangle.gameEnded").
		emit();
	}

	gameStarted(description: string, numberOfImages: u32, reward: u64, tagsRequiredPerImage: u32): void {
		new wasmlib.EventEncoder("zentangle.gameStarted").
		string(description).
		uint32(numberOfImages).
		uint64(reward).
		uint32(tagsRequiredPerImage).
		emit();
	}

	imagetagged(address: string, imageId: u32, playsPerImage: u32): void {
		new wasmlib.EventEncoder("zentangle.imagetagged").
		string(address).
		uint32(imageId).
		uint32(playsPerImage).
		emit();
	}

	paid(accuracy: string, amount: u64, bet: u64, boost: u8, player: string, position: u64): void {
		new wasmlib.EventEncoder("zentangle.paid").
		string(accuracy).
		uint64(amount).
		uint64(bet).
		uint8(boost).
		string(player).
		uint64(position).
		emit();
	}

	playRequested(address: string, amount: u64, imageId: u32): void {
		new wasmlib.EventEncoder("zentangle.playRequested").
		string(address).
		uint64(amount).
		uint32(imageId).
		emit();
	}
}
