// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export const IdxParamDescription          = 0;
export const IdxParamImageId              = 1;
export const IdxParamInputJson            = 2;
export const IdxParamNumberOfImages       = 3;
export const IdxParamOwner                = 4;
export const IdxParamPlayerAddress        = 5;
export const IdxParamResetPlayerInfo      = 6;
export const IdxParamTagsRequiredPerImage = 7;

export const IdxResultImageId       = 8;
export const IdxResultInfo          = 9;
export const IdxResultOwner         = 10;
export const IdxResultPlayerBets    = 11;
export const IdxResultPlaysPerImage = 12;
export const IdxResultResults       = 13;

export const IdxStateBets                 = 14;
export const IdxStateCreator              = 15;
export const IdxStateDescription          = 16;
export const IdxStateNumberOfImages       = 17;
export const IdxStateOwner                = 18;
export const IdxStatePendingPlay          = 19;
export const IdxStatePlayer               = 20;
export const IdxStatePlaysPerImage        = 21;
export const IdxStateProcessedImages      = 22;
export const IdxStateReward               = 23;
export const IdxStateTaggedImages         = 24;
export const IdxStateTagsRequiredPerImage = 25;
export const IdxStateValidTags            = 26;

export let keyMap: string[] = [
	sc.ParamDescription,
	sc.ParamImageId,
	sc.ParamInputJson,
	sc.ParamNumberOfImages,
	sc.ParamOwner,
	sc.ParamPlayerAddress,
	sc.ParamResetPlayerInfo,
	sc.ParamTagsRequiredPerImage,
	sc.ResultImageId,
	sc.ResultInfo,
	sc.ResultOwner,
	sc.ResultPlayerBets,
	sc.ResultPlaysPerImage,
	sc.ResultResults,
	sc.StateBets,
	sc.StateCreator,
	sc.StateDescription,
	sc.StateNumberOfImages,
	sc.StateOwner,
	sc.StatePendingPlay,
	sc.StatePlayer,
	sc.StatePlaysPerImage,
	sc.StateProcessedImages,
	sc.StateReward,
	sc.StateTaggedImages,
	sc.StateTagsRequiredPerImage,
	sc.StateValidTags,
];

export let idxMap: wasmlib.Key32[] = new Array(keyMap.length);
