// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";

export class Bet {
    amount  : i64 = 0; 
    imageId : i32 = 0; 
    player  : wasmlib.ScAgentID = new wasmlib.ScAgentID();  // player placing the bet

    static fromBytes(bytes: u8[]): Bet {
        let decode = new wasmlib.BytesDecoder(bytes);
        let data = new Bet();
        data.amount  = decode.int64();
        data.imageId = decode.int32();
        data.player  = decode.agentID();
        decode.close();
        return data;
    }

    bytes(): u8[] {
        return new wasmlib.BytesEncoder().
		    int64(this.amount).
		    int32(this.imageId).
		    agentID(this.player).
            data();
    }
}

export class ImmutableBet {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    value(): Bet {
        return Bet.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class MutableBet {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    delete(): void {
        wasmlib.delKey(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    setValue(value: Bet): void {
        wasmlib.setBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES, value.bytes());
    }

    value(): Bet {
        return Bet.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class Player {
    nDoubleBoosts  : i64 = 0;  // Number of 2x boost used in the round
    nTags          : i64 = 0;  // Number of tags made by the player in the current round
    nTrippleBoosts : i64 = 0;  // Number of 3x boosts used in the round
    playerId       : wasmlib.ScAgentID = new wasmlib.ScAgentID();  // The player

    static fromBytes(bytes: u8[]): Player {
        let decode = new wasmlib.BytesDecoder(bytes);
        let data = new Player();
        data.nDoubleBoosts  = decode.int64();
        data.nTags          = decode.int64();
        data.nTrippleBoosts = decode.int64();
        data.playerId       = decode.agentID();
        decode.close();
        return data;
    }

    bytes(): u8[] {
        return new wasmlib.BytesEncoder().
		    int64(this.nDoubleBoosts).
		    int64(this.nTags).
		    int64(this.nTrippleBoosts).
		    agentID(this.playerId).
            data();
    }
}

export class ImmutablePlayer {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    value(): Player {
        return Player.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class MutablePlayer {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    delete(): void {
        wasmlib.delKey(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    setValue(value: Player): void {
        wasmlib.setBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES, value.bytes());
    }

    value(): Player {
        return Player.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class TaggedImage {
    boost   : string = "";  // if the tags will be boosted or not
    h       : string = "";  // heights of the Tags
    imageId : i32 = 0; 
    player  : wasmlib.ScAgentID = new wasmlib.ScAgentID();  // player that has tagged this image
    w       : string = "";  // widths of the Tags
    x       : string = "";  // x top-left positions of the Tags
    y       : string = "";  // y top-left positions of the Tags

    static fromBytes(bytes: u8[]): TaggedImage {
        let decode = new wasmlib.BytesDecoder(bytes);
        let data = new TaggedImage();
        data.boost   = decode.string();
        data.h       = decode.string();
        data.imageId = decode.int32();
        data.player  = decode.agentID();
        data.w       = decode.string();
        data.x       = decode.string();
        data.y       = decode.string();
        decode.close();
        return data;
    }

    bytes(): u8[] {
        return new wasmlib.BytesEncoder().
		    string(this.boost).
		    string(this.h).
		    int32(this.imageId).
		    agentID(this.player).
		    string(this.w).
		    string(this.x).
		    string(this.y).
            data();
    }
}

export class ImmutableTaggedImage {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    value(): TaggedImage {
        return TaggedImage.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class MutableTaggedImage {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    delete(): void {
        wasmlib.delKey(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    setValue(value: TaggedImage): void {
        wasmlib.setBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES, value.bytes());
    }

    value(): TaggedImage {
        return TaggedImage.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class ValidTag {
    playTagId   : i32 = 0;  // Identifier to distinguish different tags in the same play
    player      : wasmlib.ScAgentID = new wasmlib.ScAgentID();  // player placing the bet
    taggedImage : i32 = 0; 

    static fromBytes(bytes: u8[]): ValidTag {
        let decode = new wasmlib.BytesDecoder(bytes);
        let data = new ValidTag();
        data.playTagId   = decode.int32();
        data.player      = decode.agentID();
        data.taggedImage = decode.int32();
        decode.close();
        return data;
    }

    bytes(): u8[] {
        return new wasmlib.BytesEncoder().
		    int32(this.playTagId).
		    agentID(this.player).
		    int32(this.taggedImage).
            data();
    }
}

export class ImmutableValidTag {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    value(): ValidTag {
        return ValidTag.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}

export class MutableValidTag {
    objID: i32;
    keyID: wasmlib.Key32;

    constructor(objID: i32, keyID: wasmlib.Key32) {
        this.objID = objID;
        this.keyID = keyID;
    }

    delete(): void {
        wasmlib.delKey(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    exists(): boolean {
        return wasmlib.exists(this.objID, this.keyID, wasmlib.TYPE_BYTES);
    }

    setValue(value: ValidTag): void {
        wasmlib.setBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES, value.bytes());
    }

    value(): ValidTag {
        return ValidTag.fromBytes(wasmlib.getBytes(this.objID, this.keyID, wasmlib.TYPE_BYTES));
    }
}
