// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package zentangle

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamDescription          = 0
	IdxParamImageId              = 1
	IdxParamInputJson            = 2
	IdxParamNumberOfImages       = 3
	IdxParamOwner                = 4
	IdxParamTagsRequiredPerImage = 5

	IdxResultImageId       = 6
	IdxResultOwner         = 7
	IdxResultPlayerBets    = 8
	IdxResultPlaysPerImage = 9
	IdxResultResults       = 10

	IdxStateBets                 = 11
	IdxStateCreator              = 12
	IdxStateDescription          = 13
	IdxStateNumberOfImages       = 14
	IdxStateOwner                = 15
	IdxStatePendingPlays         = 16
	IdxStatePlayers              = 17
	IdxStatePlaysPerImage        = 18
	IdxStateProcessedImages      = 19
	IdxStateReward               = 20
	IdxStateTaggedImages         = 21
	IdxStateTagsRequiredPerImage = 22
	IdxStateValidTags            = 23
)

const keyMapLen = 24

var keyMap = [keyMapLen]wasmlib.Key{
	ParamDescription,
	ParamImageId,
	ParamInputJson,
	ParamNumberOfImages,
	ParamOwner,
	ParamTagsRequiredPerImage,
	ResultImageId,
	ResultOwner,
	ResultPlayerBets,
	ResultPlaysPerImage,
	ResultResults,
	StateBets,
	StateCreator,
	StateDescription,
	StateNumberOfImages,
	StateOwner,
	StatePendingPlays,
	StatePlayers,
	StatePlaysPerImage,
	StateProcessedImages,
	StateReward,
	StateTaggedImages,
	StateTagsRequiredPerImage,
	StateValidTags,
}

var idxMap [keyMapLen]wasmlib.Key32
