// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package zentangle

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamDescription          = 0
	IdxParamImageId              = 1
	IdxParamInputJson            = 2
	IdxParamNumberOfImages       = 3
	IdxParamOwner                = 4
	IdxParamPlayerAddress        = 5
	IdxParamTagsRequiredPerImage = 6

	IdxResultImageId       = 7
	IdxResultInfo          = 8
	IdxResultOwner         = 9
	IdxResultPlayerBets    = 10
	IdxResultPlaysPerImage = 11
	IdxResultResults       = 12

	IdxStateBets                 = 13
	IdxStateCreator              = 14
	IdxStateDescription          = 15
	IdxStateNumberOfImages       = 16
	IdxStateOwner                = 17
	IdxStatePendingPlays         = 18
	IdxStatePlayers              = 19
	IdxStatePlaysPerImage        = 20
	IdxStateProcessedImages      = 21
	IdxStateReward               = 22
	IdxStateTaggedImages         = 23
	IdxStateTagsRequiredPerImage = 24
	IdxStateValidTags            = 25
)

const keyMapLen = 26

var keyMap = [keyMapLen]wasmlib.Key{
	ParamDescription,
	ParamImageId,
	ParamInputJson,
	ParamNumberOfImages,
	ParamOwner,
	ParamPlayerAddress,
	ParamTagsRequiredPerImage,
	ResultImageId,
	ResultInfo,
	ResultOwner,
	ResultPlayerBets,
	ResultPlaysPerImage,
	ResultResults,
	StateBets,
	StateCreator,
	StateDescription,
	StateNumberOfImages,
	StateOwner,
	StatePendingPlays,
	StatePlayers,
	StatePlaysPerImage,
	StateProcessedImages,
	StateReward,
	StateTaggedImages,
	StateTagsRequiredPerImage,
	StateValidTags,
}

var idxMap [keyMapLen]wasmlib.Key32
