// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package zentangle

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ImmutableCreateGameParams struct {
	id int32
}

func (s ImmutableCreateGameParams) Description() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamDescription])
}

func (s ImmutableCreateGameParams) NumberOfImages() wasmlib.ScImmutableInt32 {
	return wasmlib.NewScImmutableInt32(s.id, idxMap[IdxParamNumberOfImages])
}

func (s ImmutableCreateGameParams) TagsRequiredPerImage() wasmlib.ScImmutableInt32 {
	return wasmlib.NewScImmutableInt32(s.id, idxMap[IdxParamTagsRequiredPerImage])
}

type MutableCreateGameParams struct {
	id int32
}

func (s MutableCreateGameParams) Description() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamDescription])
}

func (s MutableCreateGameParams) NumberOfImages() wasmlib.ScMutableInt32 {
	return wasmlib.NewScMutableInt32(s.id, idxMap[IdxParamNumberOfImages])
}

func (s MutableCreateGameParams) TagsRequiredPerImage() wasmlib.ScMutableInt32 {
	return wasmlib.NewScMutableInt32(s.id, idxMap[IdxParamTagsRequiredPerImage])
}

type ImmutableInitParams struct {
	id int32
}

func (s ImmutableInitParams) Owner() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamOwner])
}

type MutableInitParams struct {
	id int32
}

func (s MutableInitParams) Owner() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamOwner])
}

type ImmutableSendTagsParams struct {
	id int32
}

func (s ImmutableSendTagsParams) InputJson() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamInputJson])
}

type MutableSendTagsParams struct {
	id int32
}

func (s MutableSendTagsParams) InputJson() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamInputJson])
}

type ImmutableSetOwnerParams struct {
	id int32
}

func (s ImmutableSetOwnerParams) Owner() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamOwner])
}

type MutableSetOwnerParams struct {
	id int32
}

func (s MutableSetOwnerParams) Owner() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamOwner])
}

type ImmutableGetPlaysPerImageParams struct {
	id int32
}

func (s ImmutableGetPlaysPerImageParams) ImageId() wasmlib.ScImmutableInt32 {
	return wasmlib.NewScImmutableInt32(s.id, idxMap[IdxParamImageId])
}

type MutableGetPlaysPerImageParams struct {
	id int32
}

func (s MutableGetPlaysPerImageParams) ImageId() wasmlib.ScMutableInt32 {
	return wasmlib.NewScMutableInt32(s.id, idxMap[IdxParamImageId])
}

type ImmutableGetResultsParams struct {
	id int32
}

func (s ImmutableGetResultsParams) ImageId() wasmlib.ScImmutableInt32 {
	return wasmlib.NewScImmutableInt32(s.id, idxMap[IdxParamImageId])
}

type MutableGetResultsParams struct {
	id int32
}

func (s MutableGetResultsParams) ImageId() wasmlib.ScMutableInt32 {
	return wasmlib.NewScMutableInt32(s.id, idxMap[IdxParamImageId])
}
