// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package zentangle

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ImmutableCreateGameParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableCreateGameParams) Description() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamDescription))
}

func (s ImmutableCreateGameParams) NumberOfImages() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.proxy.Root(ParamNumberOfImages))
}

func (s ImmutableCreateGameParams) TagsRequiredPerImage() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.proxy.Root(ParamTagsRequiredPerImage))
}

type MutableCreateGameParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableCreateGameParams) Description() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamDescription))
}

func (s MutableCreateGameParams) NumberOfImages() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.proxy.Root(ParamNumberOfImages))
}

func (s MutableCreateGameParams) TagsRequiredPerImage() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.proxy.Root(ParamTagsRequiredPerImage))
}

type ImmutableEndGameParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableEndGameParams) Mission() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamMission))
}

func (s ImmutableEndGameParams) ResetPlayerInfo() wasmtypes.ScImmutableBool {
	return wasmtypes.NewScImmutableBool(s.proxy.Root(ParamResetPlayerInfo))
}

type MutableEndGameParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableEndGameParams) Mission() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamMission))
}

func (s MutableEndGameParams) ResetPlayerInfo() wasmtypes.ScMutableBool {
	return wasmtypes.NewScMutableBool(s.proxy.Root(ParamResetPlayerInfo))
}

type ImmutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableInitParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableInitParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}

type ImmutableSendTagsParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSendTagsParams) InputJson() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamInputJson))
}

type MutableSendTagsParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSendTagsParams) InputJson() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamInputJson))
}

type ImmutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetOwnerParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetOwnerParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}

type ImmutableGetPlayerInfoParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableGetPlayerInfoParams) PlayerAddress() wasmtypes.ScImmutableString {
	return wasmtypes.NewScImmutableString(s.proxy.Root(ParamPlayerAddress))
}

type MutableGetPlayerInfoParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableGetPlayerInfoParams) PlayerAddress() wasmtypes.ScMutableString {
	return wasmtypes.NewScMutableString(s.proxy.Root(ParamPlayerAddress))
}

type ImmutableGetPlaysPerImageParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableGetPlaysPerImageParams) ImageId() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.proxy.Root(ParamImageId))
}

type MutableGetPlaysPerImageParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableGetPlaysPerImageParams) ImageId() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.proxy.Root(ParamImageId))
}

type ImmutableGetResultsParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableGetResultsParams) ImageId() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.proxy.Root(ParamImageId))
}

type MutableGetResultsParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableGetResultsParams) ImageId() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.proxy.Root(ParamImageId))
}
